name: tase_highd
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - tqdm
  - pyyaml
  - h5py
  - pip:
      - tensorboard
      - torch
      - pygame
